name: Commit with version

on:
  workflow_dispatch:

jobs:
  build:
    name: Commit with Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update test file
        run: |
          date > test
      - name: Commit
        run: |
          git add test
          git commit -m "Update test file"
          git push


