name: Commit with version
on:
  workflow_dispatch:
jobs:
  build:
    name: Commit with Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up JDK
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
        with:
          java-version: '17'
      - name: setup git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Update test file
        run: |
          date > test
      - name: Commit
        run: |
          git add test
          git commit -m "Update test file"
          git push
