name: Schedule
on:
  push:
  schedule:
    - cron: '*/15 * * * *' # Every 15 minutes
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Set up JDK
        uses: actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde # v1
        with:
          java-version: '17'
      - name: Build with Gradle
        run: echo Starting build
